'------------------------------------------------------------------------------
' <auto-generated>
'     Questo codice è stato generato da uno strumento.
'     Eventuali modifiche potrebbero causare un comportamento errato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class [Global_asax]

End Class
